- README.md
Following the advice from Andrew Lock [1] we should change the badge to only show the build result for the latest build in master as we usually don't care whether some PR build failed.
[1] https://andrewlock.net/building-an-open-source-github-project-using-azure-devops/#bonus-adding-build-badges-to-your-readme-md
> Fix build badge to only show master

- mc/CodeAnalysis/Binding/Binder.cs
- mc/Program.cs
It was failing in runtime for expressions of the kind "(1 + 2) * 3"
> Added binding support for parenthesized expressions

- mc/CodeAnalysis/Binding/BoundBinaryExpression.cs
- mc/CodeAnalysis/Binding/BoundNodeKind.cs
Hi there. Noticed this during the last video and thought I'd send you a pull request. The Kind property isn't used yet due to the use of the is keyword in the Evaluator.
Really enjoying the series so far. Keep it up! 👍
> Fixed Kind Property of  BoundBinaryExpression

- Minsk.Tests/Minsk.Tests.csproj
- azure-pipelines.yml
This PR will enable viewing test results in azure pipelines.
To enable this i added the [XunitXML.TestLogger](https://www.nuget.org/packages/XunitXml.TestLogger/) to the test project and modified the `azure-pipelines.yml`.
> Publish test results to azure pipelines

- src/Minsk/CodeAnalysis/Compilation.cs
The parameter syntaxTree was assigned to the property SyntaxTree twice, once in both constructors of Compilation when only needs to be done once.
> Removed duplicate assignment of SyntaxTree in Compilation ctor

- src/Minsk/CodeAnalysis/Syntax/SyntaxTree.cs
The declaration of a local variable diagnostics in the SyntaxTree constructor is not needed. Assigned Diagnostics from the parser directly to the Diagnostics property of the SyntaxTree.
> Removed local variable diagnostics in SyntaxTree constructor

- .vscode/extensions.json
This will cause VSCode to recommend the C# extension if it's not installed.
> Added recommended extensions file for vscode

- src/Minsk.Tests/CodeAnalysis/EvaluationTests.cs
- src/Minsk/CodeAnalysis/Lowering/Lowerer.cs
This matters if the upper bound expression has side effects.
NB: I targeted this PR to your episode branch, since it's not merged yet.
> Evaluate the upper bound only once in a for loop

- src/Minsk/CodeAnalysis/Binding/BoundConditionalGotoStatement.cs
- src/Minsk/CodeAnalysis/Binding/BoundTreeRewriter.cs
- src/Minsk/CodeAnalysis/Evaluator.cs
- src/Minsk/CodeAnalysis/Lowering/Lowerer.cs
Ok, this is a suggestion, but `BoundConditionalGotoStatement` uses a double negation to convey its meaning, which I find unnatural when reading such code:
This replaces `JumpIfFalse` with `JumpIfTrue` which removes the double negation.
NB: I targeted this PR to your episode branch, since it's not merged yet.
> Remove double negation in BoundConditionalGotoStatement usage

- src/.editorconfig
This will make sure that the IDE & VS Code generate fields with an underscore prefix when using refactorings such as "Create and initialize field" so you don't have to fix this up later. Not only that, but it will also stop inserting `this.` :100:
Before:
After:
> Enforce underscore prefix for fields

- src/Minsk/CodeAnalysis/Syntax/SyntaxToken.cs
- src/mc/MinskRepl.cs
The current check for whether the submission is incomplete is simply looking for any syntax errors. This often results in false positives because syntax errors could be arbitrarily deep in the tree and/or unrelated to the fact that I haven't finished typing.
For example: typing something like `(1 + )` and hitting enter will result in ever adding more blank lines because there's nothing I could do at this point to fix the error. In this case the error was made accidentally as opposed to being an incomplete submission.
After this PR, typing `(1 + )` will submit and show the syntax error. Similarly with things like `1a` or `{ var a = 1; }`. Basically this PR should result in a much better experience when you make typos because it will alert you of the error as opposed to an unexpected new …
> Check whether the last token is missing as opposed to a looking for arbitrary syntax errors

- src/Minsk/CodeAnalysis/Binding/Binder.cs
- src/Minsk/CodeAnalysis/Symbols/FunctionSymbol.cs
I think that 'Parameters' would be better in plural (you named it also Arguments when calling a function).
> rename parameter to parameters (plural)

- src/Minsk.Tests/CodeAnalysis/EvaluationTests.cs
- src/Minsk/CodeAnalysis/Binding/Binder.cs
- src/Minsk/CodeAnalysis/Binding/BoundScope.cs
- src/Minsk/CodeAnalysis/DiagnosticBag.cs
I'm not sure if that's something you'd actually want to change, but this PR prevents variables and functions from having the same name, which could be confusing. As an added bonus, there's less code duplication.
You can still shadow a symbol defined in an outer scope, even if it's of a different type, as shadowing was an intended feature.
Before:
After:
> Use a single namespace for all symbol types

- src/mc/MinskRepl.cs
- src/mc/TextSpanComparer.cs
This is in order to display diagnostic messages ordered by occurrence in the input.
e.g. for the input "x = 10 * y" the following diagnostics are displayed:
(1, 10): Variable 'y' doesn't exist.
x = 10 * **y**
(1, 1): Variable 'x' doesn't exist.
**x** = 10 * y
It makes more sense to show them in the reverse order. This pull request orders diagnostic messages by the span property.
> Sort diagnostics by span before showing them

- src/Minsk.Tests/CodeAnalysis/EvaluationTests.cs
- src/Minsk/CodeAnalysis/Syntax/Parser.cs
Hello Immo!
First of all, just say thanks for doing this amazing job, i'm learning and enjoying a lot following this course.
If found a small issue when parsing parameters or arguments, it can cause infinite loops if they are not valid
```
print("Hello"=)
```
or
```
function hi(name: string =) 
{
print("Hello " + name)
}
```
Next task should be prevent cascading errors
> Prevent infinite loops when parsing invalid arguments or parameter

- .gitignore
I'm using NCrunch for running the tests, and the keep popping up as untracked files, however, they're safe to ignore since you don't need to customize it (runs out of the box for this solution). The default Visual Studio gitignore already ignores NCrunch generated files, but it's a bit outdated.
> Update ignore pattern for NCrunch

- src/Minsk/CodeAnalysis/Binding/BoundNodePrinter.cs
- src/Minsk/CodeAnalysis/Symbols/SymbolPrinter.cs
- src/Minsk/IO/TextWriterExtensions.cs
I'm not even sure if this PR is a good change, so feel free to ignore it completely. 😄
It makes use of the `SyntaxFacts` class to get the text to print, for the sake of the DRY principle.
> Use SyntaxFacts to get the text to print

- src/Minsk.Tests/CodeAnalysis/EvaluationTests.cs
- src/Minsk/CodeAnalysis/Binding/Binder.cs
Fixed the highlighted span location for exceeding/missing arguments.
Also report errors for every mismatching argument type, ignoring arguments of unbound error expressions.
> Minor fixes to binding of call arguments

- src/Minsk.Tests/CodeAnalysis/EvaluationTests.cs
- src/Minsk/CodeAnalysis/Binding/Binder.cs
I have found an exception in the evaluator when you create a function without a name. So:
```
function (): bool
{
return true
}
```
The syntax-tree will contain an error (found '(' but expected identifier). But in the Evaluator it will still crash.
Also added some other Evaluator tests to test more function-related diagnostics.
> Fix an exception when functionname is empty. Also added evaluator tests.

- src/Minsk/CodeAnalysis/Binding/BoundNodePrinter.cs
- src/Minsk/CodeAnalysis/Binding/ControlFlowGraph.cs
- src/Minsk/CodeAnalysis/DiagnosticBag.cs
- Escape backslashes in dot files - I found inconsistencies in the Graphviz docs in this regard, but dot won't display a backslash in the generated graph unless you escape it
- Use an `IndentedTextWriter` for graph node labels, otherwise one would be created automatically for each label
- You [can use commas or semicolons](https://www.graphviz.org/doc/info/lang.html) to separate attributes in dot files, so use a comma
- Fixed diagnostic message
> Some minor changes

- src/Minsk.Tests/CodeAnalysis/EvaluationTests.cs
- src/Minsk/CodeAnalysis/Binding/Binder.cs
- src/Minsk/CodeAnalysis/Binding/BoundScope.cs
- src/Minsk/CodeAnalysis/DiagnosticBag.cs
This is a follow-up to #54. I wasn't sure if you were going to accept that one so I didn't polish the diagnostics. This PR fixes this.
> Better error messages for mismatched symbol types

- src/Minsk.Tests/CodeAnalysis/EvaluationTests.cs
- src/Minsk/CodeAnalysis/Binding/ControlFlowGraph.cs
Fixed an exception while evaluating control flow for empty functions. e.g.
```
function add(a: int, b: int): int
{
}
```
When the body of the function is empty, the `BasicBlock` for the function has no statements. When `AllPathsReturn` tries to get the last statement to check it is a `BoundNodeKind.ReturnStatement`, an exception is thrown because the sequence is empty.
`Unhandled Exception: System.InvalidOperationException: Sequence contains no elements`
> Fix control flow evaluation for empty functions

- .vscode/tasks.json
Now we can launch debugger on linux.
> Fix solution filename casing on tasks.json

- src/Minsk.Tests/Minsk.Tests.csproj
- src/Minsk/CodeAnalysis/Binding/Binder.cs
- src/Minsk/IO/TextWriterExtensions.cs
- src/mc/Program.cs
This fixes some minor stuff I noticed after watching episode 15. The changes are self-explanatory.
The one less obvious thing is that `Console.ForegroundColor` always sends color codes to `Console.Out`, so when trying to write colored text to `Console.Error`, I first make sure that both `Console.Out` and `Console.Error` are not redirected.
> Some cleanup

- src/Minsk/CodeAnalysis/Compilation.cs
- src/msi/MinskRepl.cs
- src/msi/Repl.cs
*Based on Episode 16 PR #83.*
Fixes to Meta command handling
* Use generic `GetCustomAttribute` method for meta command detection
* Meta commands work on both static and instance methods
* Change error message for meta command usage to reflect how the command is actually invoked (remove comma)
- Before: `command <arg1>, <arg2>`
- After: `command <arg1> <arg2>`
* `Compilation.GetSymbols` method also yields built-in functions
* `#ls` and `#dump` commands work with the built-in symbols even if the submission history is empty (by using an empty compilation)
`#ls` now shows the following:
```
» #ls
function input(): string
function print(text: string)
function rnd(max: int): int
```
Dumping a built-in function writes only its signature (as there is no body to dump):
```
» #dump print
function …
```
> Minor fixes to Meta commands

- src/msi/Repl.cs
*Based on Episode 16 PR #83.*
Makes the `#help` command also print out the parameters of a command.
Changes the output of `#help` to:
```
» #help
#cls           Clears the screen
#dump <functionName>
Shows bound tree of a given function
#help          Shows help
#load <path>
Loads a script file
#ls            Lists all symbols
#reset         Clears all previous submissions
#showProgram   Shows the bound tree
#showTree      Shows the parse tree
```
> Show command parameters in #help

- src/msi/MinskRepl.cs
The field `_loadingSubmissions` is assigned from the non-static method `LoadSubmissions`.
> Make _loadingSubmissions a instance field

- src/Minsk/CodeAnalysis/Compilation.cs
If a submission re-defines a built-in, the `GetSymbols` method (used by the `#ls` meta-command) will fetch the built-in symbols before the redefinition. This results in `#ls` displaying the wrong symbol (because the binder will first do the submitted symbols)
fixes a bug in previously merged PR #84
> Fix GetSymbols for shadowed built-ins

- src/Minsk/CodeAnalysis/Binding/Binder.cs
- src/Minsk/CodeAnalysis/DiagnosticBag.cs
`_function` is always null in that case. This also changes the error message since we're not in a function.
> Fix null reference exception

- src/Minsk/CodeAnalysis/DiagnosticBag.cs
`minskName` is always null here
> Use metadataName for ReportRequiredTypeAmbiguous

- src/Minsk/CodeAnalysis/Compilation.cs
Maybe not a huge performance increase, but the reflection of BuiltInFunctions should be out of the loop because those do not change with each submission. Maybe even the whole `foreach` on the builtinfunction-list should be out of the loop?
> Moving reflection part out of the loop.

- src/Minsk/CodeAnalysis/Compilation.cs
Matches `Compilation.Evaluate(...)` behaviour.
Otherwise we ignore any parsing errors and try to emit the program anyway.
e.g. This currently compiles to IL and runs
```
function main()
let greeting = "Hello
print(greeting)
```
> Return parse diagnostics before emitting

- src/Minsk/CodeAnalysis/Emit/Emitter.cs
- src/Minsk/CodeAnalysis/Evaluator.cs
Constant values are only used for conditional gotos and dead code elimination, the obvious use for them is missing ;-)
> Use computed constant values

- src/Minsk/CodeAnalysis/Lowering/Lowerer.cs
This is half a PR, half a Question:
Should the constructed statements in `RewriteConditionalGotoStatement()` be rewriten like the ones in `RewriteIfStatement()` or not?
> Rewrite constructed statements(?)

- src/Minsk/CodeAnalysis/Emit/Emitter.cs
Fixes #97.
- The first commit flattens the expression tree and chooses the most appropriate overload of `String.Concat`
- The second commit adds constant folding, so that `(a + "foo") + ("bar" + b)` ends up emitting `String.Concat(a, "foobar", b)`
This is based on `episode22`, as it uses constant folding. I did not write unit tests though, since I don't know how you'd like to test the emitter.
> Optimize string concatenation

- src/Minsk/CodeAnalysis/Binding/Binder.cs
- src/Minsk/CodeAnalysis/Compilation.cs
- src/Minsk/CodeAnalysis/DiagnosticBag.cs
Syntax-related errors were not taken into account when emitting IL, and the compiler would crash on some inputs.
This avoids binding the program when there are syntax errors, and propagates the diagnostics.
This will necessarily require some adjustment if you introduce warnings.
> Propagate lexer/parser diagnostics through the binder

- src/Minsk.Tests/CodeAnalysis/Syntax/LexerTests.cs
- src/Minsk/CodeAnalysis/Syntax/Lexer.cs
I wanted to create a few functions named `str2`, `str3` etc in order to test my other PR, and I was surprised when the compiler went boom. 😄
This allows digits (except as the first character) and underscores in identifiers.
> Allow digits and underscores in identifiers

- .vscode/launch.json
- .vscode/tasks.json
- azure-pipelines.yml
- build.cmd
- build.sh
- msc.cmd
- msc.sh
- msi.cmd
- msi.sh
- samples/Directory.Build.props
- samples/Directory.Build.targets
- samples/samples.sln
- src/Directory.Build.props
- src/Directory.Build.targets
- src/Minsk.Generators/Minsk.Generators.csproj
- src/Minsk.Generators/SyntaxNodeGetChildrenGenerator.cs
- src/Minsk.Tests/Minsk.Tests.csproj
- src/Minsk/Minsk.csproj
- src/minsk.sln
- src/msc/msc.csproj
- src/msi/msi.csproj
These are the updates that I wanted to include it in #106 but it was already a large enough change. 😇
Removed BOM from remaining files
Added/Updated Comments where possible
Don't append short TFMs and RIDs to output paths
**Use `Microsoft.NET.Compilers.ToolSet` that contains both CoreCLR and NETCLR compilers** (Fixes #137)
Enable scripts to be invoked from different directory than the script's directory.
Updated tasks to have most used workflows, for those, who hate to go to terminal every time.
Construct compiler command line from properties, so that it's easy to edit and reason about.
Some are latest versions (xunit packages)
Some are stable versions (immutable collections & test sdk packages)
Not all projects needed to be packed/published. Setting these properties will prevent that. …
> Few updates to Build infra

- src/Minsk.Generators/CurlyIndenter.cs
- src/Minsk.Generators/SyntaxNodeGetChildrenGenerator.cs
Hi @terrajobst,
This is quite a minor PR.
It comes from a hack I sometimes use when writing files that regularly have `header -> content -> footer` structures.
The hack is to write the header with a disposable class instantiated with a `using` statement so that when the closing brace is hit and it goes out of scope the footer is taken care of automatically.
In the case of the code-generator it's certainly not a big deal, I'm submitting mainly to get your opinion on the approach and style.
Thanks,
Claudio
> Re-styled SourceGenerator with CurlyIndenter.

- azure-pipelines.yml
Modified the azure-pipelines template to build both the `Debug` and `Release` configurations for both `Windows` and `Linux` operating systems.
The solution uses a parameterized azure-pipeline template. This means that the OSs and Configurations can be configured in the Web UI when queueing a manual build.
I chose not to use the [`matrix` job strategy](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#matrix) in the template as the matrix-strategy as it did not allow me the fidelity I wanted when setting Display Names for the jobs. *E.g. note that OS is not a simple string, but an object containing the `vmImage` and a human readable `name`.*
I also found matrix strategies to be harder to reason about, while I suspect most programmers will understand a foreach-loop over a …
> Build both Debug and Release configurations for all major OS during CI

- src/Directory.Build.props
This makes JetBrains Rider aware of the generated file in its design-time build, since it doesn't currently have generators support.
> Add generators hack for Rider

- src/Minsk/CodeAnalysis/Emit/Emitter.cs
Mono.Cecil.Rocks contains three main optimisations: Macro-re-write,
Branch-re-write, and immediate integer compaction. The `Optimize` method
runs all of these against the given method body. This means that
immediate values that _can_ be represented with a smaller encoding
will be converted as well as the existing re-writes performed by
`OptimizeMacros`.
> Call `Optimize` Rather than `OptimizeMacros`
